responsive layout, first page
LucaDorinAnton/my-website pull request #11
Opened 2024-02-15 11:24 UTC by VictorRadoi

responsive layout added and some parts from first page

2024-02-15 14:26 UTC, VictorRadoi commented on website/lib/presentation/desktop/home_page/home_page_desktop.dart
fnf

2024-02-20 21:40 UTC, LucaDorinAnton requested changes
Please clean up PR so that I can review it thoroughly

2024-02-20 21:40 UTC, LucaDorinAnton commented on new_flutter_website/.fvmrc
> +{
Can we call this folder `flutter`?

2024-02-20 21:40 UTC, LucaDorinAnton commented on new_flutter_website/.gitignore
include to root `.gitignore`, 
also please add to it:
- .vscode
- android
- ios
- linux
- macos
- windows 
- website
- web

also please remove from a PR (I can't review a PR with 300 files in it)

(I tried running the build without those and it worked)

2024-03-26 12:54 UTC, LucaDorinAnton approved these changes

2024-03-26 12:54 UTC, merged